//
//  TabCustomerViewController.h
//  Wangli
//
//  Created by yeqiang on 2018/3/28.
//  Copyright © 2018年 yeqiang. All rights reserved.
//

#import "BaseViewCtrl.h"

@interface TabCustomerViewController : BaseViewCtrl

@end

//{
//    "content": [{
//        "typeName": "手工筛选",
//        "memberChooseBeans": [{
//            "name": "交易类型",
//            "chooseBeans": [{
//                "key": "经销商",
//                "value": "经销商",
//                "option": "IN"
//            }, {
//                "key": "直销",
//                "value": "直销",
//                "option": "IN"
//            }, {
//                "key": "竞争对手客户",
//                "value": "竞争对手客户",
//                "option": "IN"
//            }, {
//                "key": "下游终端客户",
//                "value": "下游终端客户",
//                "option": "IN"
//            }],
//            "memberFeild": "transactionType",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "负责人",
//            "chooseBeans": [{
//                "key": "我的",
//                "value": "MINE",
//                "option": null
//            }, {
//                "key": "我下属的",
//                "value": "UNDERMINE",
//                "option": null
//            }, {
//                "key": "不属于任何人的",
//                "value": "NOBELONG",
//                "option": null
//            }],
//            "memberFeild": null,
//            "hidden": false,
//            "multiSelect": true,
//            "special": true
//        }, {
//            "name": "部门",
//            "chooseBeans": [{
//                "key": "南方销售办公室",
//                "value": "110",
//                "option": "EQ"
//            }, {
//                "key": "华峰氨纶总部",
//                "value": "111",
//                "option": "EQ"
//            }, {
//                "key": "绍兴办事处",
//                "value": "112",
//                "option": "EQ"
//            }, {
//                "key": "张家港办事处",
//                "value": "113",
//                "option": "EQ"
//            }, {
//                "key": "广东办事处",
//                "value": "114",
//                "option": "EQ"
//            }, {
//                "key": "福建办事处",
//                "value": "115",
//                "option": "EQ"
//            }, {
//                "key": "诸暨办事处",
//                "value": "116",
//                "option": "EQ"
//            }, {
//                "key": "海宁办事处",
//                "value": "117",
//                "option": "EQ"
//            }, {
//                "key": "瑞安办事处",
//                "value": "118",
//                "option": "EQ"
//            }, {
//                "key": "常熟办事处",
//                "value": "119",
//                "option": "EQ"
//            }, {
//                "key": "外贸亚洲部",
//                "value": "120",
//                "option": "EQ"
//            }, {
//                "key": "外贸欧洲部",
//                "value": "121",
//                "option": "EQ"
//            }, {
//                "key": "外贸美洲部",
//                "value": "122",
//                "option": "EQ"
//            }, {
//                "key": "外贸非洲部",
//                "value": "123",
//                "option": "EQ"
//            }, {
//                "key": "东莞办事处",
//                "value": "124",
//                "option": "EQ"
//            }],
//            "memberFeild": "office.id",
//            "hidden": true,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "领域",
//            "chooseBeans": [{
//                "key": "圆机",
//                "value": "field_圆机",
//                "option": null
//            }, {
//                "key": "包纱",
//                "value": "field_包纱",
//                "option": null
//            }, {
//                "key": "棉包芯",
//                "value": "field_棉包芯",
//                "option": null
//            }, {
//                "key": "织带",
//                "value": "field_织带",
//                "option": null
//            }],
//            "memberFeild": null,
//            "hidden": false,
//            "multiSelect": false,
//            "special": true
//        }, {
//            "name": "用途",
//            "chooseBeans": [{
//                "key": "单面机",
//                "value": "application_单面机",
//                "option": null
//            }, {
//                "key": "双面机",
//                "value": "application_双面机",
//                "option": null
//            }, {
//                "key": "小圆机",
//                "value": "application_小圆机",
//                "option": null
//            }, {
//                "key": "普通空包",
//                "value": "application_普通空包",
//                "option": null
//            }, {
//                "key": "高速空包一体机",
//                "value": "application_高速空包一体机",
//                "option": null
//            }, {
//                "key": "棉包芯",
//                "value": "application_棉包芯",
//                "option": null
//            }, {
//                "key": "机包",
//                "value": "application_机包",
//                "option": null
//            }, {
//                "key": "并线",
//                "value": "application_并线",
//                "option": null
//            }, {
//                "key": "超柔",
//                "value": "application_超柔",
//                "option": null
//            }, {
//                "key": "不倒绒",
//                "value": "application_不倒绒",
//                "option": null
//            }, {
//                "key": "花边",
//                "value": "application_花边",
//                "option": null
//            }, {
//                "key": "网布",
//                "value": "application_网布",
//                "option": null
//            }, {
//                "key": "经编平布",
//                "value": "application_经编平布",
//                "option": null
//            }],
//            "memberFeild": null,
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "账期",
//            "chooseBeans": [{
//                "key": "0",
//                "value": "0",
//                "option": "EQ"
//            }, {
//                "key": "30",
//                "value": "30",
//                "option": "EQ"
//            }, {
//                "key": "45",
//                "value": "45",
//                "option": "EQ"
//            }, {
//                "key": "60",
//                "value": "60",
//                "option": "EQ"
//            }, {
//                "key": "90",
//                "value": "90",
//                "option": "EQ"
//            }, {
//                "key": "90",
//                "value": "90",
//                "option": "GT"
//            }],
//            "memberFeild": "creditModifyDate",
//            "hidden": true,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "额度",
//            "chooseBeans": [{
//                "key": "10~30万",
//                "value": "10,30",
//                "option": "BT"
//            }, {
//                "key": "30~50万",
//                "value": "30,50",
//                "option": "BT"
//            }, {
//                "key": "50~100万",
//                "value": "50,100",
//                "option": "BT"
//            }, {
//                "key": "100~200万",
//                "value": "100,200",
//                "option": "BT"
//            }, {
//                "key": "200~500万",
//                "value": "200,500",
//                "option": "BT"
//            }, {
//                "key": "500万+",
//                "value": "500",
//                "option": "GT"
//            }],
//            "memberFeild": "credit",
//            "hidden": true,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "风险级别",
//            "chooseBeans": [{
//                "key": "正常",
//                "value": "正常",
//                "option": "IN"
//            }, {
//                "key": "预警",
//                "value": "预警",
//                "option": "IN"
//            }, {
//                "key": "危险",
//                "value": "危险",
//                "option": "IN"
//            }, {
//                "key": "高危",
//                "value": "高危",
//                "option": "IN"
//            }],
//            "memberFeild": "riskLevel",
//            "hidden": true,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "最后一天成交日期",
//            "chooseBeans": [{
//                "key": "超出九十天未成交",
//                "value": "2018-04-28 17:03:31",
//                "option": "LEDATE"
//            }],
//            "memberFeild": "lastTransactionDays",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }]
//    }, {
//        "typeName": "快速检索",
//        "memberChooseBeans": [{
//            "name": "不限",
//            "chooseBeans": null,
//            "memberFeild": null,
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "我的所有客户",
//            "chooseBeans": null,
//            "memberFeild": "MINE",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "本月需催款客户",
//            "chooseBeans": null,
//            "memberFeild": "NEED_REMINDERS",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "本月计划完成率小于70%的客户",
//            "chooseBeans": null,
//            "memberFeild": "DEMAND_UNDER_SEVENTY_PERCENT",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "前三个月发货量前50的客户",
//            "chooseBeans": null,
//            "memberFeild": "SHIPMENTS",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "本月货已发票未开客户",
//            "chooseBeans": null,
//            "memberFeild": "DELIVERY_NOT_INVOICED",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "3个月以上未交易客户",
//            "chooseBeans": null,
//            "memberFeild": "NOTRADE",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "本月新增客户",
//            "chooseBeans": null,
//            "memberFeild": "NEWCREATED",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "高危风险客户清单",
//            "chooseBeans": null,
//            "memberFeild": "HIGHRISK",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "竞争对手优质客户清单",
//            "chooseBeans": null,
//            "memberFeild": "GOOD_CUSTOMERS_OF_COMPETITORS",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "机台数前10名",
//            "chooseBeans": null,
//            "memberFeild": "MACHINE_NUMBER",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "前三个月开机率前十名",
//            "chooseBeans": null,
//            "memberFeild": "MACHINE_PERCENT",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "我下属的客户",
//            "chooseBeans": null,
//            "memberFeild": "UNDERMINE",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "所有无主客户",
//            "chooseBeans": null,
//            "memberFeild": "NOBELONG",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }]
//    }, {
//        "typeName": "排序",
//        "memberChooseBeans": [{
//            "name": "不限",
//            "chooseBeans": null,
//            "memberFeild": null,
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "按名字拼音首字母排序(A-Z)",
//            "chooseBeans": null,
//            "memberFeild": "ORDER_BY_NAME",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "按客户欠款金额排序(从大到小)",
//            "chooseBeans": null,
//            "memberFeild": "ORDER_BY_DEBT_AMOUNT",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "按客户信贷额度排序(从大到小)",
//            "chooseBeans": null,
//            "memberFeild": "ORDER_BY_CREDIT_AMOUNT",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "按客户欠款账期排序(从大到小)",
//            "chooseBeans": null,
//            "memberFeild": "ORDER_BY_CREDIT_DEBT_DATE",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "按客户信贷账期顺序(从大到小)",
//            "chooseBeans": null,
//            "memberFeild": "ORDER_BY_CREDIT_MODIFY_DATE",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "按最近成交日期排序(从后到前)",
//            "chooseBeans": null,
//            "memberFeild": "ORDER_BY_TRANSATION_DAY",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "按客户风险等级排序(高危到一般)",
//            "chooseBeans": null,
//            "memberFeild": "ORDER_BY_RISK_LEVEL",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "按客户价值等级排序(A-D)",
//            "chooseBeans": null,
//            "memberFeild": "ORDER_BY_VELUA_LEVEL",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "按客户前三个月发货数量排序(A-D)",
//            "chooseBeans": null,
//            "memberFeild": "ORDER_BY_DELIVERY_NUMBER",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "按客户公司成立日期排序(从前到后)",
//            "chooseBeans": null,
//            "memberFeild": "ORDER_BY_COMPANY_CREATEDATE",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "按客户注册资金排序(从大到小)",
//            "chooseBeans": null,
//            "memberFeild": "ORDER_BY_REGISTERED_CAPITAL",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "按客户编码排序(从大到小)",
//            "chooseBeans": null,
//            "memberFeild": "ORDER_BY_REGISTERED_CAPITAL",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }, {
//            "name": "按客户创建日期排序(从后到前)",
//            "chooseBeans": null,
//            "memberFeild": "ORDER_BY_CNUMBER",
//            "hidden": false,
//            "multiSelect": false,
//            "special": false
//        }]
//    }]
//}
