//
//  StoreMo.h
//  Wangli
//
//  Created by yeqiang on 2019/4/29.
//  Copyright © 2019年 jiuyisoft. All rights reserved.
//

#import <JSONModel/JSONModel.h>

NS_ASSUME_NONNULL_BEGIN

@interface StoreMo : JSONModel

@property (nonatomic, copy) NSString <Optional> *lastUpdateByName;  //;  //"林武龙",
@property (nonatomic, copy) NSString <Optional> *numberOfGuides;  //"",
@property (nonatomic, strong) NSDictionary <Optional> *city;
@property (nonatomic, copy) NSString <Optional> *whetherToMonopolize;  //true,
@property (nonatomic, copy) NSString <Optional> *intoTheStore;  //"",
@property (nonatomic, copy) NSString <Optional> *afterSalesCall;  //"",
@property (nonatomic, strong) NSDictionary <Optional> *province;
@property (nonatomic, copy) NSString <Optional> *legalPerson;  //null,
@property (nonatomic, copy) NSString <Optional> *contactNumber;  //"",
@property (nonatomic, copy) NSString <Optional> *storeName;  //"qqqqqqqqq测试机",
@property (nonatomic, assign) long long id;  //58,
@property (nonatomic, copy) NSString <Optional> *sampleDoorStyle;  //"",
@property (nonatomic, strong) NSMutableArray <Optional> *brand;  //null,
@property (nonatomic, copy) NSString <Optional> *storeArea;  //"",
@property (nonatomic, strong) NSDictionary <Optional> *area;
@property (nonatomic, copy) NSString <Optional> *brandName;  //"",
@property (nonatomic, copy) NSString <Optional> *shipment;  //"",
@property (nonatomic, copy) NSString <Optional> *createByName;  //"林武龙",
@property (nonatomic, copy) NSString <Optional> *lastModifiedDate;  //"2019-04-16 11:45:16",
@property (nonatomic, copy) NSString <Optional> *lastModifiedBy;  //"林武龙",
@property (nonatomic, copy) NSString <Optional> *retailVolume;  //"",
@property (nonatomic, copy) NSString <Optional> *customerName;  //"永康市王力工贸有限公司",
@property (nonatomic, copy) NSString <Optional> *communityActivityThisMonth;  //"",
@property (nonatomic, copy) NSString <Optional> *createdDate;  //"2019-04-16 11:45:16",
@property (nonatomic, copy) NSString <Optional> *compareSalesItems;  //"",
@property (nonatomic, copy) NSString <Optional> *forPublicHouseholds;  //"",
@property (nonatomic, copy) NSString <Optional> *createdBy;  //"林武龙",
@property (nonatomic, copy) NSString <Optional> *storeAddress;  //"",
@property (nonatomic, copy) NSString <Optional> *turnoverRate;  //"",
@property (nonatomic, copy) NSString <Optional> *faxNumber;  //"",
@property (nonatomic, copy) NSString <Optional> *provinceName;  //"湖南省",
@property (nonatomic, copy) NSString <Optional> *numberOfSampleDoors;  //"",
@property (nonatomic, copy) NSString <Optional> *qualitySituation;  //"",
@property (nonatomic, strong) NSDictionary <Optional> *customer;
@property (nonatomic, assign) BOOL deleted;  //"",

@end

NS_ASSUME_NONNULL_END


//{
//    "manageStatusTitle": null,
//    "operator": null,
//    "liked": -8,
//    "legalName": "张工",
//    "whetherToMonopolize": false,
//    "businessScopeTitle": null,
//    "afterSalesCall": null,
//    "province": {
//        "provinceName": "安徽",
//        "id": 12,
//        "provinceId": "340000"
//    },
//    "areaName": null,
//    "id": 17321,
//    "favoritedCount": null,
//    "sampleDoorStyle": "36",
//    "brand": [{
//        "brandName": "华爵",
//        "createdDate": "2019-04-09 14:07:42",
//        "brandDesc": "华爵",
//        "lastModifiedDate": "2019-04-09 14:07:47",
//        "createdBy": "管理员",
//        "lastModifiedBy": "管理员",
//        "id": 3,
//        "sort": 0
//    }, {
//        "brandName": "能诚",
//        "createdDate": "2019-04-09 14:08:12",
//        "brandDesc": "能诚",
//        "lastModifiedDate": "2019-04-09 14:08:17",
//        "createdBy": "管理员",
//        "lastModifiedBy": "管理员",
//        "id": 4,
//        "sort": 0
//    }, {
//        "brandName": "王力",
//        "createdDate": "2019-04-09 14:08:48",
//        "brandDesc": "王力",
//        "lastModifiedDate": "2019-04-09 14:08:54",
//        "createdBy": "管理员",
//        "lastModifiedBy": "管理员",
//        "id": 5,
//        "sort": 0
//    }],
//    "area": null,
//    "brandName": "王力 能诚 华爵",
//    "createByName": "管理员",
//    "shipment": null,
//    "createProcess": null,
//    "sort": 10,
//    "customerName": null,
//    "compareSalesItems": "对此情况",
//    "forPublicHouseholds": "安徽水利开发有限公司",
//    "storeAddress": "地址",
//    "provinceName": "安徽",
//    "lastUpdateByName": "管理员",
//    "numberOfGuides": "14",
//    "attachments": [],
//    "city": null,
//    "updateText": null,
//    "dealerScopeTitle": null,
//    "intoTheStore": null,
//    "cityName": null,
//    "legalPerson": null,
//    "viewed": -8,
//    "contactNumber": null,
//    "storeName": "测试门店1",
//    "storeArea": "13",
//    "favorited": -8,
//    "store_code": "wlmd17321",
//    "lastModifiedDate": "2019-07-17 14:45:32",
//    "lastModifiedBy": "管理员",
//    "retailVolume": null,
//    "likedCount": 0,
//    "communityActivityThisMonth": null,
//    "createdDate": "2019-07-17 14:45:32",
//    "createdBy": "管理员",
//    "turnoverRate": null,
//    "viewedCount": 0,
//    "faxNumber": null,
//    "numberOfSampleDoors": "25",
//    "qualitySituation": null,
//    "customer": {
//        "storeNumber": null,
//        "cityNumber": null,
//        "bail": null,
//        "operator": null,
//        "legalName": "张工",
//        "accountBank": null,
//        "registeredAddress": null,
//        "areaName": null,
//        "companyPhone": null,
//        "statusKey": "formal",
//        "provinceNumber": "340000",
//        "id": 17803,
//        "orgName": "安徽水利开发有限公司",
//        "creditLevelKey": "A",
//        "avatarUrl": null,
//        "areaNumber": null,
//        "taxNumber": null,
//        "marketBailQuentity": null,
//        "businessScope": "组件",
//        "sort": 10,
//        "afterSalesNumber": null,
//        "superiorChain": null,
//        "provinceName": "安徽",
//        "cooperationTypeValue": "直销客户",
//        "region": null,
//        "targetQuantity": null,
//        "assessmentAgreement": null,
//        "crmNumber": "2913216",
//        "statusValue": "正式",
//        "growthRate": null,
//        "creditLevelValue": "A",
//        "sapNumber": "2913216",
//        "operatorName": "未分配",
//        "cooperationTypeKey": "straight_pin",
//        "exclusiveShopNumber": null,
//        "memberLevelValue": "普通",
//        "firstDistributorName": null,
//        "cityName": null,
//        "registeredCapital": null,
//        "simpleSpell": "ahslkfyxgs",
//        "natureManagement": null,
//        "createdOperatorName": null,
//        "faxAreaCode": null,
//        "lastModifiedDate": "2019-07-08 18:01:21",
//        "lastModifiedBy": "系统自动创建",
//        "abbreviation": null,
//        "faxPhoneNumber": null,
//        "marketBail": null,
//        "brandNames": null,
//        "createdDate": "2019-07-08 18:01:21",
//        "createdBy": "系统自动创建",
//        "companyAddress": null,
//        "memberLevelKey": "ordinary",
//        "annualTargetCompletionRate": null
//    }
//}
