//
//  PersonBusinessCell.h
//  Wangli
//
//  Created by yeqiang on 2018/12/11.
//  Copyright © 2018年 jiuyisoft. All rights reserved.
//

#import <UIKit/UIKit.h>
#import "LinkManBusinessMo.h"

NS_ASSUME_NONNULL_BEGIN

@interface PersonBusinessCell : UITableViewCell

@property (nonatomic, strong) LinkManBusinessMo *model;
@property (nonatomic, strong) UIView *lineView;
- (void)loadData:(LinkManBusinessMo *)model;

@end

NS_ASSUME_NONNULL_END

//{
//    "id": 69,
//    "sort": 1,
//    "createdDate": 1545739143684,
//    "lastModifiedDate": 1545739149498,
//    "createdBy": "17721180295",
//    "lastModifiedBy": "17721180295",
//    "content": "测试商机",
//    "title": "测试商机",
//    "operatorName": "唐旺",
//    "statusValue": "",
//    "statusKey": "",
//    "importantKey": "general",
//    "amount": 123456,
//    "typeKey": "",
//    "clue": {
//        "id": 33,
//        "sort": 1,
//        "createdDate": 1545474372712,
//        "lastModifiedDate": 1545729656341,
//        "createdBy": "17721180295",
//        "lastModifiedBy": "17721180295"
//    },
//    "clueTitle": "测试关联情报",
//    "submitDate": "2018-12-25 19:58",
//    "resourceValue": "老客户介绍",
//    "resourceKey": "customer_introduce",
//    "quotedPrice": [
//                    {
//                        "id": 27,
//                        "sort": 1,
//                        "createdDate": 1545809142665,
//                        "lastModifiedDate": 1545812359534,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "涂曦",
//                        "member": {
//                            "id": 234,
//                            "sort": 1,
//                            "createdDate": 1545101063761,
//                            "lastModifiedDate": 1546079142209,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "crmNumber": "200182",
//                            "simpleSpell": "ahst",
//                            "sapNumber": "200182",
//                            "abbreviation": "安徽圣泰",
//                            "orgName": "安徽圣泰太阳能科技有限责任公司",
//                            "arOperatorName": "未分配",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商",
//                            "memberLevelValue": "普通"
//                        },
//                        "operator": {
//                            "id": 64,
//                            "sort": 10,
//                            "createdDate": 1543497342873,
//                            "lastModifiedDate": 1546756486912,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "1021597",
//                            "name": "徐明广",
//                            "username": "42",
//                            "title": "销售代表",
//                            "oaCode": "1021597",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 18,
//                        "sort": 1,
//                        "createdDate": 1545806189237,
//                        "lastModifiedDate": 1545806189237,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "涂曦",
//                        "member": {
//                            "id": 236,
//                            "sort": 1,
//                            "createdDate": 1545101063706,
//                            "lastModifiedDate": 1546079142220,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "statusKey": "potential",
//                            "crmNumber": "200160",
//                            "simpleSpell": "fszh",
//                            "sapNumber": "200160",
//                            "abbreviation": "佛山纵横",
//                            "orgName": "佛山市纵横企业有限公司",
//                            "arOperatorName": "唐旺",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商"
//                        },
//                        "operator": {
//                            "id": 64,
//                            "sort": 10,
//                            "createdDate": 1543497342873,
//                            "lastModifiedDate": 1546756486912,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "1021597",
//                            "name": "徐明广",
//                            "username": "42",
//                            "title": "销售代表",
//                            "oaCode": "1021597",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 20,
//                        "sort": 1,
//                        "createdDate": 1545807355249,
//                        "lastModifiedDate": 1545807355249,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "涂曦",
//                        "member": {
//                            "id": 234,
//                            "sort": 1,
//                            "createdDate": 1545101063761,
//                            "lastModifiedDate": 1546079142209,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "crmNumber": "200182",
//                            "simpleSpell": "ahst",
//                            "sapNumber": "200182",
//                            "abbreviation": "安徽圣泰",
//                            "orgName": "安徽圣泰太阳能科技有限责任公司",
//                            "arOperatorName": "未分配",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商",
//                            "memberLevelValue": "普通"
//                        },
//                        "operator": {
//                            "id": 64,
//                            "sort": 10,
//                            "createdDate": 1543497342873,
//                            "lastModifiedDate": 1546756486912,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "1021597",
//                            "name": "徐明广",
//                            "username": "42",
//                            "title": "销售代表",
//                            "oaCode": "1021597",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 22,
//                        "sort": 1,
//                        "createdDate": 1545808769604,
//                        "lastModifiedDate": 1545808769604,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "涂曦",
//                        "member": {
//                            "id": 234,
//                            "sort": 1,
//                            "createdDate": 1545101063761,
//                            "lastModifiedDate": 1546079142209,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "crmNumber": "200182",
//                            "simpleSpell": "ahst",
//                            "sapNumber": "200182",
//                            "abbreviation": "安徽圣泰",
//                            "orgName": "安徽圣泰太阳能科技有限责任公司",
//                            "arOperatorName": "未分配",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商",
//                            "memberLevelValue": "普通"
//                        },
//                        "operator": {
//                            "id": 64,
//                            "sort": 10,
//                            "createdDate": 1543497342873,
//                            "lastModifiedDate": 1546756486912,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "1021597",
//                            "name": "徐明广",
//                            "username": "42",
//                            "title": "销售代表",
//                            "oaCode": "1021597",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 38,
//                        "sort": 1,
//                        "createdDate": 1545908589998,
//                        "lastModifiedDate": 1545911271160,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "金显聪",
//                        "member": {
//                            "id": 236,
//                            "sort": 1,
//                            "createdDate": 1545101063706,
//                            "lastModifiedDate": 1546079142220,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "statusKey": "potential",
//                            "crmNumber": "200160",
//                            "simpleSpell": "fszh",
//                            "sapNumber": "200160",
//                            "abbreviation": "佛山纵横",
//                            "orgName": "佛山市纵横企业有限公司",
//                            "arOperatorName": "唐旺",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商"
//                        },
//                        "operator": {
//                            "id": 48,
//                            "sort": 10,
//                            "createdDate": 1543497342813,
//                            "lastModifiedDate": 1546829996449,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "1016078",
//                            "name": "杨建树",
//                            "username": "26",
//                            "title": "高级销售代表",
//                            "oaCode": "1016078",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 35,
//                        "sort": 1,
//                        "createdDate": 1545903548153,
//                        "lastModifiedDate": 1545903548153,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "金显聪",
//                        "member": {
//                            "id": 236,
//                            "sort": 1,
//                            "createdDate": 1545101063706,
//                            "lastModifiedDate": 1546079142220,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "statusKey": "potential",
//                            "crmNumber": "200160",
//                            "simpleSpell": "fszh",
//                            "sapNumber": "200160",
//                            "abbreviation": "佛山纵横",
//                            "orgName": "佛山市纵横企业有限公司",
//                            "arOperatorName": "唐旺",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商"
//                        },
//                        "operator": {
//                            "id": 48,
//                            "sort": 10,
//                            "createdDate": 1543497342813,
//                            "lastModifiedDate": 1546829996449,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "1016078",
//                            "name": "杨建树",
//                            "username": "26",
//                            "title": "高级销售代表",
//                            "oaCode": "1016078",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 25,
//                        "sort": 1,
//                        "createdDate": 1545808920423,
//                        "lastModifiedDate": 1545808920423,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "涂曦",
//                        "member": {
//                            "id": 234,
//                            "sort": 1,
//                            "createdDate": 1545101063761,
//                            "lastModifiedDate": 1546079142209,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "crmNumber": "200182",
//                            "simpleSpell": "ahst",
//                            "sapNumber": "200182",
//                            "abbreviation": "安徽圣泰",
//                            "orgName": "安徽圣泰太阳能科技有限责任公司",
//                            "arOperatorName": "未分配",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商",
//                            "memberLevelValue": "普通"
//                        },
//                        "operator": {
//                            "id": 64,
//                            "sort": 10,
//                            "createdDate": 1543497342873,
//                            "lastModifiedDate": 1546756486912,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "1021597",
//                            "name": "徐明广",
//                            "username": "42",
//                            "title": "销售代表",
//                            "oaCode": "1021597",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 31,
//                        "sort": 1,
//                        "createdDate": 1545902062417,
//                        "lastModifiedDate": 1545902062417,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "孙飞立",
//                        "member": {
//                            "id": 236,
//                            "sort": 1,
//                            "createdDate": 1545101063706,
//                            "lastModifiedDate": 1546079142220,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "statusKey": "potential",
//                            "crmNumber": "200160",
//                            "simpleSpell": "fszh",
//                            "sapNumber": "200160",
//                            "abbreviation": "佛山纵横",
//                            "orgName": "佛山市纵横企业有限公司",
//                            "arOperatorName": "唐旺",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商"
//                        },
//                        "operator": {
//                            "id": 3,
//                            "sort": 10,
//                            "createdDate": 1543497342593,
//                            "lastModifiedDate": 1546526259761,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "1022654",
//                            "name": "李跃飞",
//                            "username": "53",
//                            "title": "高级销售代表",
//                            "oaCode": "1022645",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 21,
//                        "sort": 1,
//                        "createdDate": 1545807425774,
//                        "lastModifiedDate": 1545807425774,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "涂曦",
//                        "member": {
//                            "id": 234,
//                            "sort": 1,
//                            "createdDate": 1545101063761,
//                            "lastModifiedDate": 1546079142209,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "crmNumber": "200182",
//                            "simpleSpell": "ahst",
//                            "sapNumber": "200182",
//                            "abbreviation": "安徽圣泰",
//                            "orgName": "安徽圣泰太阳能科技有限责任公司",
//                            "arOperatorName": "未分配",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商",
//                            "memberLevelValue": "普通"
//                        },
//                        "operator": {
//                            "id": 64,
//                            "sort": 10,
//                            "createdDate": 1543497342873,
//                            "lastModifiedDate": 1546756486912,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "1021597",
//                            "name": "徐明广",
//                            "username": "42",
//                            "title": "销售代表",
//                            "oaCode": "1021597",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 26,
//                        "sort": 1,
//                        "createdDate": 1545809028991,
//                        "lastModifiedDate": 1545809029301,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "涂曦",
//                        "member": {
//                            "id": 234,
//                            "sort": 1,
//                            "createdDate": 1545101063761,
//                            "lastModifiedDate": 1546079142209,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "crmNumber": "200182",
//                            "simpleSpell": "ahst",
//                            "sapNumber": "200182",
//                            "abbreviation": "安徽圣泰",
//                            "orgName": "安徽圣泰太阳能科技有限责任公司",
//                            "arOperatorName": "未分配",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商",
//                            "memberLevelValue": "普通"
//                        },
//                        "operator": {
//                            "id": 64,
//                            "sort": 10,
//                            "createdDate": 1543497342873,
//                            "lastModifiedDate": 1546756486912,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "1021597",
//                            "name": "徐明广",
//                            "username": "42",
//                            "title": "销售代表",
//                            "oaCode": "1021597",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 28,
//                        "sort": 1,
//                        "createdDate": 1545879498583,
//                        "lastModifiedDate": 1545911660329,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "翁小伟",
//                        "member": {
//                            "id": 234,
//                            "sort": 1,
//                            "createdDate": 1545101063761,
//                            "lastModifiedDate": 1546079142209,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "crmNumber": "200182",
//                            "simpleSpell": "ahst",
//                            "sapNumber": "200182",
//                            "abbreviation": "安徽圣泰",
//                            "orgName": "安徽圣泰太阳能科技有限责任公司",
//                            "arOperatorName": "未分配",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商",
//                            "memberLevelValue": "普通"
//                        },
//                        "operator": {
//                            "id": 1,
//                            "sort": 10,
//                            "createdDate": 1543497342573,
//                            "lastModifiedDate": 1546858061606,
//                            "createdBy": "15167156690",
//                            "lastModifiedBy": "1022654",
//                            "name": "刘启明",
//                            "title": "营销分析员",
//                            "oaCode": "1022654",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 24,
//                        "sort": 1,
//                        "createdDate": 1545808852996,
//                        "lastModifiedDate": 1545808852996,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "涂曦",
//                        "member": {
//                            "id": 234,
//                            "sort": 1,
//                            "createdDate": 1545101063761,
//                            "lastModifiedDate": 1546079142209,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "crmNumber": "200182",
//                            "simpleSpell": "ahst",
//                            "sapNumber": "200182",
//                            "abbreviation": "安徽圣泰",
//                            "orgName": "安徽圣泰太阳能科技有限责任公司",
//                            "arOperatorName": "未分配",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商",
//                            "memberLevelValue": "普通"
//                        },
//                        "operator": {
//                            "id": 64,
//                            "sort": 10,
//                            "createdDate": 1543497342873,
//                            "lastModifiedDate": 1546756486912,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "1021597",
//                            "name": "徐明广",
//                            "username": "42",
//                            "title": "销售代表",
//                            "oaCode": "1021597",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 29,
//                        "sort": 1,
//                        "createdDate": 1545888647555,
//                        "lastModifiedDate": 1545911640257,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "林友录",
//                        "member": {
//                            "id": 234,
//                            "sort": 1,
//                            "createdDate": 1545101063761,
//                            "lastModifiedDate": 1546079142209,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "crmNumber": "200182",
//                            "simpleSpell": "ahst",
//                            "sapNumber": "200182",
//                            "abbreviation": "安徽圣泰",
//                            "orgName": "安徽圣泰太阳能科技有限责任公司",
//                            "arOperatorName": "未分配",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商",
//                            "memberLevelValue": "普通"
//                        },
//                        "operator": {
//                            "id": 4,
//                            "sort": 10,
//                            "createdDate": 1543497342600,
//                            "lastModifiedDate": 1546514456694,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "18888996001",
//                            "name": "刘景喜",
//                            "username": "56",
//                            "title": "区域销售经理",
//                            "oaCode": "1022680",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 19,
//                        "sort": 1,
//                        "createdDate": 1545806722103,
//                        "lastModifiedDate": 1545806722103,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "涂曦",
//                        "member": {
//                            "id": 234,
//                            "sort": 1,
//                            "createdDate": 1545101063761,
//                            "lastModifiedDate": 1546079142209,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "crmNumber": "200182",
//                            "simpleSpell": "ahst",
//                            "sapNumber": "200182",
//                            "abbreviation": "安徽圣泰",
//                            "orgName": "安徽圣泰太阳能科技有限责任公司",
//                            "arOperatorName": "未分配",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商",
//                            "memberLevelValue": "普通"
//                        },
//                        "operator": {
//                            "id": 64,
//                            "sort": 10,
//                            "createdDate": 1543497342873,
//                            "lastModifiedDate": 1546756486912,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "1021597",
//                            "name": "徐明广",
//                            "username": "42",
//                            "title": "销售代表",
//                            "oaCode": "1021597",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 42,
//                        "sort": 1,
//                        "createdDate": 1545916661758,
//                        "lastModifiedDate": 1545999600716,
//                        "createdBy": "18021647031",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "唐旺",
//                        "member": {
//                            "id": 236,
//                            "sort": 1,
//                            "createdDate": 1545101063706,
//                            "lastModifiedDate": 1546079142220,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "statusKey": "potential",
//                            "crmNumber": "200160",
//                            "simpleSpell": "fszh",
//                            "sapNumber": "200160",
//                            "abbreviation": "佛山纵横",
//                            "orgName": "佛山市纵横企业有限公司",
//                            "arOperatorName": "唐旺",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商"
//                        },
//                        "operator": {
//                            "id": 79,
//                            "sort": 10,
//                            "createdDate": 1543497342937,
//                            "lastModifiedDate": 1546853150813,
//                            "createdBy": "15858562128",
//                            "lastModifiedBy": "1013121",
//                            "name": "劳建勳",
//                            "username": "59",
//                            "title": "销售助理",
//                            "oaCode": "1013121",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        },
//                        "createOperator": {
//                            "id": 79,
//                            "sort": 10,
//                            "createdDate": 1543497342937,
//                            "lastModifiedDate": 1546853150813,
//                            "createdBy": "15858562128",
//                            "lastModifiedBy": "1013121",
//                            "name": "劳建勳",
//                            "username": "59",
//                            "title": "销售助理",
//                            "oaCode": "1013121",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        }
//                    },
//                    {
//                        "id": 30,
//                        "sort": 1,
//                        "createdDate": 1545901995407,
//                        "lastModifiedDate": 1545911501383,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "孙飞立",
//                        "member": {
//                            "id": 234,
//                            "sort": 1,
//                            "createdDate": 1545101063761,
//                            "lastModifiedDate": 1546079142209,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "crmNumber": "200182",
//                            "simpleSpell": "ahst",
//                            "sapNumber": "200182",
//                            "abbreviation": "安徽圣泰",
//                            "orgName": "安徽圣泰太阳能科技有限责任公司",
//                            "arOperatorName": "未分配",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商",
//                            "memberLevelValue": "普通"
//                        },
//                        "operator": {
//                            "id": 3,
//                            "sort": 10,
//                            "createdDate": 1543497342593,
//                            "lastModifiedDate": 1546526259761,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "1022654",
//                            "name": "李跃飞",
//                            "username": "53",
//                            "title": "高级销售代表",
//                            "oaCode": "1022645",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    },
//                    {
//                        "id": 23,
//                        "sort": 1,
//                        "createdDate": 1545808817719,
//                        "lastModifiedDate": 1545808817719,
//                        "createdBy": "17721180295",
//                        "lastModifiedBy": "17721180295",
//                        "operatorName": "涂曦",
//                        "member": {
//                            "id": 234,
//                            "sort": 1,
//                            "createdDate": 1545101063761,
//                            "lastModifiedDate": 1546079142209,
//                            "createdBy": "system",
//                            "lastModifiedBy": "system",
//                            "statusValue": "潜在",
//                            "crmNumber": "200182",
//                            "simpleSpell": "ahst",
//                            "sapNumber": "200182",
//                            "abbreviation": "安徽圣泰",
//                            "orgName": "安徽圣泰太阳能科技有限责任公司",
//                            "arOperatorName": "未分配",
//                            "frOperatorName": "未分配",
//                            "srOperatorName": "未分配",
//                            "cooperationTypeValue": "供应商",
//                            "memberLevelValue": "普通"
//                        },
//                        "operator": {
//                            "id": 64,
//                            "sort": 10,
//                            "createdDate": 1543497342873,
//                            "lastModifiedDate": 1546756486912,
//                            "createdBy": "15167156698",
//                            "lastModifiedBy": "1021597",
//                            "name": "徐明广",
//                            "username": "42",
//                            "title": "销售代表",
//                            "oaCode": "1021597",
//                            "department": {
//                                "id": 1,
//                                "sort": 100,
//                                "createdDate": 1543497296440,
//                                "lastModifiedDate": 1545831978687,
//                                "createdBy": "15167156690",
//                                "lastModifiedBy": "15167156690",
//                                "name": "营销部-禁用"
//                            }
//                        },
//                        "businessChance": {
//                            "id": 69,
//                            "sort": 1,
//                            "createdDate": 1545739143684,
//                            "lastModifiedDate": 1545739149498,
//                            "createdBy": "17721180295",
//                            "lastModifiedBy": "17721180295"
//                        }
//                    }
//                    ],
//    "typeValue": "",
//    "businessNumber": "AXSJ20181225001",
//    "customerContact": "赵",
//    "transactionDate": "2018-12-28",
//    "operator": {
//        "id": 79,
//        "sort": 10,
//        "createdDate": 1543497342937,
//        "lastModifiedDate": 1546853150813,
//        "createdBy": "15858562128",
//        "lastModifiedBy": "1013121",
//        "name": "劳建勳",
//        "username": "59",
//        "title": "销售助理",
//        "oaCode": "1013121",
//        "department": {
//            "id": 1,
//            "sort": 100,
//            "createdDate": 1543497296440,
//            "lastModifiedDate": 1545831978687,
//            "createdBy": "15167156690",
//            "lastModifiedBy": "15167156690",
//            "name": "营销部-禁用"
//        }
//    },
//    "abbreviation": "测试",
//    "competitorBehaviorset": [],
//    "friendDealerSet": [],
//    "businessJournalSet": [],
//    "importantValue": "一般",
//    "favorited": -8,
//    "viewed": -8,
//    "viewedCount": 0,
//    "liked": -8,
//    "likedCount": 0
//}
